"""
pages/explainability.py — Explainability

Shows why a device or the overall network was classified as high risk.
Feature importance values are MOCK/DEMO until SHAP / attention weights
from the real model are connected.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from frontend.components.charts import feature_importance_chart
from frontend.components.metrics import demo_badge, info_metric_card, section_header
from frontend.services.mock_predictions import PredictionResult
from frontend.utils.constants import RISK_COLORS, STAGE_COLORS


def _device_selector(pred: PredictionResult) -> str:
    high_risk = [d for d in pred.risky_devices if d.risk_score >= 0.65]
    options   = [d.device_name for d in high_risk]
    if not options:
        options = [d.device_name for d in pred.risky_devices]
    return st.selectbox("Select device", options, key="expl_device_select")


def _feature_detail_table(features: list[dict]) -> None:
    rows = []
    for f in features:
        rows.append({
            "Feature":     f["feature"],
            "Importance":  f"{f['importance']:.3f}",
            "Observed":    f.get("value",    "—"),
            "Baseline":    f.get("baseline", "—"),
            "Delta":       _compute_delta(f),
        })
    df = pd.DataFrame(rows)
    st.dataframe(df, use_container_width=True, hide_index=True)


def _compute_delta(f: dict) -> str:
    """Try to compute a readable delta between observed and baseline."""
    try:
        obs  = float(str(f.get("value", "0")).split("/")[0].replace("±","").strip())
        base = float(str(f.get("baseline","0")).split("/")[0].replace("±","").strip())
        ratio = obs / base if base else 0
        if ratio > 2:
            return f"↑ {ratio:.1f}×"
        elif ratio < 0.5:
            return f"↓ {1/ratio:.1f}×"
        return "~"
    except Exception:
        return "—"


def _explanation_narrative(device_name: str, pred: PredictionResult) -> None:
    """Human-readable explanation paragraph."""
    device = next((d for d in pred.risky_devices if d.device_name == device_name), None)
    if device is None:
        return

    color = RISK_COLORS.get(device.risk_level, "#3b82f6")
    stage_color = STAGE_COLORS.get(device.current_stage, "#3b82f6")

    st.markdown(
        f"""
<div style="background:#0f172a;border:1px solid {color}33;border-left:4px solid {color};
     border-radius:10px;padding:16px 20px;margin-bottom:12px">
  <div style="color:#94a3b8;font-size:0.75rem;font-weight:600;text-transform:uppercase;
              margin-bottom:8px">Risk Explanation — {device_name}</div>
  <div style="color:#cbd5e1;font-size:0.9rem;line-height:1.7">
    <b style="color:{color}">{device_name}</b> ({device.ip}) was assigned a risk score of
    <b style="color:{color}">{device.risk_score:.0%}</b> ({device.risk_level}).<br><br>
    The primary driver is the
    <b style="color:#f1f5f9">SYN rate</b>, which is 14× above the network baseline,
    indicating a port-scanning or SYN-flood pattern characteristic of the
    <b style="color:{stage_color}">{device.current_stage}</b> stage.<br><br>
    The model predicts this device will progress to
    <b style="color:{STAGE_COLORS.get(device.predicted_stage, '#fff')}">{device.predicted_stage}</b>
    within the next 5 time steps if unchecked.
  </div>
  <div style="color:#475569;font-size:0.75rem;margin-top:10px">
    ⚙️ This explanation is a DEMO narrative. Real explanations will be generated by
    SHAP values / attention weights from the trained World Model.
  </div>
</div>
        """,
        unsafe_allow_html=True,
    )


def _global_feature_importance(pred: PredictionResult) -> None:
    section_header(
        "Global Feature Importance",
        "Which features drive the overall network risk score (DEMO — mock values)",
    )

    fig = feature_importance_chart(pred.contributing_features)
    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

    st.caption(
        "📌 Feature importance values are placeholder mock data. "
        "They will be replaced by SHAP values from the trained World Model."
    )


def _counterfactual_placeholder() -> None:
    """What-if analysis placeholder."""
    section_header(
        "What-If Analysis (Placeholder)",
        "How would the risk score change if specific features were different?",
    )
    st.markdown(
        '<div style="background:#1e2d40;border:2px dashed #1d4ed8;border-radius:8px;'
        'padding:18px 22px">'
        '<div style="color:#60a5fa;font-weight:700;margin-bottom:8px">⚙️ Counterfactual Engine — Not Yet Connected</div>'
        '<div style="color:#64748b;font-size:0.85rem">'
        'This section will allow analysts to ask: <i>"If the SYN rate were below 2/s, '
        'what would the risk score be?"</i><br><br>'
        'The counterfactual engine will be powered by the World Model\'s internal '
        'state representation once the ML backend is integrated.'
        '</div>'
        '</div>',
        unsafe_allow_html=True,
    )


# ── Public render function ────────────────────────────────────────────────────

def render(pred: PredictionResult, df: pd.DataFrame | None = None) -> None:
    st.markdown(
        '<h2 style="color:#f1f5f9;margin-bottom:0">💡 Explainability</h2>'
        '<p style="color:#64748b;margin-top:2px">'
        'Why was this device or network segment classified as high risk?</p>',
        unsafe_allow_html=True,
    )

    demo_badge()

    # ── Device-level explanation ───────────────────────────────────────────────
    section_header("Device-Level Risk Explanation")

    col_sel, col_kpi = st.columns([1, 3])
    with col_sel:
        selected_device = _device_selector(pred)
    with col_kpi:
        device = next((d for d in pred.risky_devices if d.device_name == selected_device), None)
        if device:
            c1, c2, c3, c4 = st.columns(4)
            with c1:
                info_metric_card("Risk Score", f"{device.risk_score:.0%}",
                                 color=RISK_COLORS.get(device.risk_level, "#3b82f6"))
            with c2:
                info_metric_card("Risk Level", device.risk_level,
                                 color=RISK_COLORS.get(device.risk_level, "#3b82f6"))
            with c3:
                info_metric_card("Current Stage", device.current_stage,
                                 color=STAGE_COLORS.get(device.current_stage, "#3b82f6"))
            with c4:
                info_metric_card("Predicted Stage", device.predicted_stage,
                                 color=STAGE_COLORS.get(device.predicted_stage, "#3b82f6"))

    _explanation_narrative(selected_device, pred)

    st.divider()

    # ── Per-device feature chart ───────────────────────────────────────────────
    section_header(
        f"Feature Contributions — {selected_device}",
        "Relative importance of each feature to this device's risk score",
    )

    col_chart, col_table = st.columns([1.3, 1])
    with col_chart:
        fig = feature_importance_chart(pred.contributing_features)
        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})
    with col_table:
        st.markdown("**Feature Detail Table**")
        _feature_detail_table(pred.contributing_features)

    st.divider()

    # ── Global importance ──────────────────────────────────────────────────────
    _global_feature_importance(pred)

    st.divider()

    # ── What-if placeholder ────────────────────────────────────────────────────
    _counterfactual_placeholder()
