import pandas as pd
import numpy as np
from pathlib import Path

INPUT = Path("data/simulated/simulated_packets.csv")
OUTPUT = Path("data/simulated/network_states.csv")

WINDOW_SECONDS = 10


# ------------------------------------------------------------
# Load packet telemetry
# ------------------------------------------------------------

df = pd.read_csv(INPUT)

df["timestamp"] = pd.to_datetime(
    df["timestamp"],
    format="mixed"
)

df = df.sort_values("timestamp").reset_index(drop=True)

print(f"Loaded {len(df):,} packet events")


# ------------------------------------------------------------
# Create 10-second windows
# ------------------------------------------------------------

df["window_start"] = (
    df["timestamp"].dt.floor(f"{WINDOW_SECONDS}s")
)


# ------------------------------------------------------------
# Aggregate packets into network states
# ------------------------------------------------------------

states = (
    df.groupby("window_start")
    .agg(
        total_packets=("packet_size", "count"),

        total_bytes=("packet_size", "sum"),

        unique_src_ips=("src_ip", "nunique"),

        unique_dst_ips=("dst_ip", "nunique"),

        unique_dst_ports=("dst_port", "nunique"),

        unique_src_ports=("src_port", "nunique"),

        mean_packet_size=("packet_size", "mean"),

        packet_size_std=("packet_size", "std"),

        packet_size_min=("packet_size", "min"),

        packet_size_max=("packet_size", "max"),

        mean_ttl=("ttl", "mean"),

        ttl_std=("ttl", "std"),

        mean_tcp_window=("tcp_window", "mean"),

        tcp_window_std=("tcp_window", "std"),

        syn_count=("syn", "sum"),

        ack_count=("ack", "sum"),

        rst_count=("rst", "sum"),

        fin_count=("fin", "sum"),
    )
    .reset_index()
)


# ------------------------------------------------------------
# Replace NaN generated by std() in small windows
# ------------------------------------------------------------

numeric_columns = states.select_dtypes(
    include=np.number
).columns

states[numeric_columns] = (
    states[numeric_columns]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


# ------------------------------------------------------------
# Determine attack state of each window
#
# We use the dominant attack type in the window.
# ------------------------------------------------------------

labels = (
    df.groupby("window_start")["attack_type"]
    .agg(lambda x: x.value_counts().index[0])
    .reset_index()
)

states = states.merge(
    labels,
    on="window_start",
    how="left"
)


# ------------------------------------------------------------
# Binary malicious label
# ------------------------------------------------------------

states["label"] = (
    states["attack_type"] != "Benign"
).astype(int)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

OUTPUT.parent.mkdir(parents=True, exist_ok=True)

states.to_csv(OUTPUT, index=False)

print()
print("=" * 60)
print("NETWORK STATE GENERATION COMPLETE")
print("=" * 60)

print(f"Output windows : {len(states):,}")
print(f"Output file    : {OUTPUT}")
print(f"Window size    : {WINDOW_SECONDS} seconds")

print()
print("State distribution:")
print(states["attack_type"].value_counts())

print()
print("State columns:")
print(states.columns.tolist())

print("=" * 60)